name: Benchmark REST

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configurar Java y sbt
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: sbt
      - name: Instalar wrk
        run: sudo apt-get update && sudo apt-get install -y wrk
      - name: Ejecutar benchmark
        run: |
          chmod +x scripts/benchmark_rest.sh
          ./scripts/benchmark_rest.sh
      - name: Subir resultados
        uses: actions/upload-artifact@v4
        with:
          name: resultados-benchmark
          path: docs/performance/base-*.md
