name: Scala CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: entystal
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: sbt
      - name: Instalar cliente PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Instalar Xvfb
        run: sudo apt-get install -y xvfb
      - name: Inicializar base de datos
        env:
          PGUSER: postgres
          PGPASSWORD: password
        run: psql -h localhost -d entystal -f core/sql/entystal_schema.sql

      - name: Formateo y pruebas
        env:
          PGUSER: postgres
          PGPASSWORD: password
        run: |
          sbt scalafmtAll
          xvfb-run --auto-servernum sbt test
