name: ZAP Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */5 * *'

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configurar Java y sbt
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: sbt
      - name: Arrancar RestServer
        run: |
          sbt "rest/run" &
          for i in {1..20}; do
            if curl -s http://localhost:8080/metrics > /dev/null; then
              break
            fi
            sleep 5
          done
      - name: Escaneo con OWASP ZAP
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080'
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap-report
          cmd_options: '-a'
      - name: Verificar alertas altas
        run: |
          HIGH=$(jq '[.site[]?.alerts[]? | select(.riskdesc | test("High"))] | length' report_json.json)
          echo "Alertas severas: $HIGH"
          if [ "$HIGH" -gt 0 ]; then
            echo "Se encontraron alertas de severidad alta" >&2
            exit 1
          fi
      - name: Publicar reporte ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_md.md
            report_json.json
